version: '3'

vars:
  BINARY_NAME: promify-goss

tasks:
  clean:
    cmds:
      - rm -fv ./build/{{.BINARY_NAME}}-linux-amd64 ./{{.BINARY_NAME}} 
  build:
    cmds:
      - go build -o ./build/{{.BINARY_NAME}}-linux-amd64 .
      - ln -s ./build/{{.BINARY_NAME}}-linux-amd64 ./{{.BINARY_NAME}}
  install:
    cmds:
      - cp -vf ./build/{{.BINARY_NAME}} /usr/local/bin/
