version: '3'

vars:
  BINARY_NAME: promify-goss

tasks:
  clean:
    cmds:
      - rm -fv ./build/{{.BINARY_NAME}}-linux-amd64 ./{{.BINARY_NAME}}
  lintci:
    cmds:
      - golangci-lint run ./...
  lint:
    cmds:
      - golint ./...
  test:
    cmds:
      - go test -v ./... -cover
  build:
    cmds:
      - go build -o ./build/{{.BINARY_NAME}}-linux-amd64 .
      - ln -s ./build/{{.BINARY_NAME}}-linux-amd64 ./{{.BINARY_NAME}}
  install:
    cmds:
      - sudo cp -vf ./build/{{.BINARY_NAME}}-linux-amd64 /usr/local/bin/{{.BINARY_NAME}}
